# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
    "github.com/containernetworking/plugins/plugins/ipam/dhcp",
    "github.com/containernetworking/plugins/plugins/ipam/host-local",
    "github.com/containernetworking/plugins/plugins/ipam/host-local/backend/allocator",
    "github.com/containernetworking/plugins/plugins/ipam/static",
    "github.com/containernetworking/plugins/plugins/main/bridge",
    "github.com/containernetworking/plugins/plugins/main/host-device",
    "github.com/containernetworking/plugins/plugins/main/ipvlan",
    "github.com/containernetworking/plugins/plugins/main/loopback",
    "github.com/containernetworking/plugins/plugins/main/macvlan",
    "github.com/containernetworking/plugins/plugins/main/ptp",
    "github.com/containernetworking/plugins/plugins/main/vlan",
    "github.com/containernetworking/plugins/plugins/meta/bandwidth",
    "github.com/containernetworking/plugins/plugins/meta/flannel",
    "github.com/containernetworking/plugins/plugins/meta/portmap",
    "github.com/containernetworking/plugins/plugins/meta/tuning",
]

[[constraint]]
  name = "github.com/pelletier/go-toml"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sylabs/sif"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/containers/image"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/opencontainers/image-spec"

[[constraint]]
  branch = "master"
  name = "github.com/containerd/cgroups"

[[constraint]]
  branch = "master"
  name = "github.com/opencontainers/runtime-spec"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/opencontainers/selinux"
  version = "v1.0.0-rc1"

[[constraint]]
  name = "github.com/seccomp/libseccomp-golang"
  version = "v0.9.0"

[[constraint]]
  name = "github.com/kr/pty"
  version = "v1.1.3"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/containernetworking/plugins"
    unused-packages = false

# patched fork from github.com/opencontainers/image-tools
[[override]]
  branch = "master"
  name = "github.com/opencontainers/image-tools"
  source = "https://github.com/sylabs/image-tools"

# patched fork from github.com/golang/crypto
[[override]]
  branch = "master"
  name = "golang.org/x/crypto"
  source = "https://github.com/sylabs/golang-x-crypto"

[[override]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[override]]
  revision = "da99009bbb1165d1ac5688b5c81d2f589d418341"
  name = "github.com/docker/docker"

[[constraint]]
  name = "github.com/sylabs/json-resp"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/kelseyhightower/envconfig"
